env:
  es6: true
  node: true

extends: 'airbnb-base'

globals:
  assert: true
  browser: true
  expect: true

parserOptions:
  ecmaVersion: 6

root: true

rules:
  global-require: 'off'
  import/no-extraneous-dependencies: 0
  indent:
    - 'error'
    - 2
    - SwitchCase: 1
  max-len:
    - 'error'
    - 120
  new-cap:
    - 'error'
    - newIsCap: true
  require-jsdoc:
    - 'warn'
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
  strict: 'off'
  valid-jsdoc:
    - 'warn'
    - requireReturn: false
      matchDescription: '.+'
